### ISSUE TITLE
shapes (6,6) and (4,4) not aligned: 6 (dim 1) != 4 (dim 0)

### ISSUE THREAD

**Issue by lakshmip001** [crigroup/raveutils#10]
I am trying to use this raveutils with UR5 robot with the function plan_cartesian_twist. I get the error as shown below:

```
traj = ru.planning.plan_cartesian_twist(self.robot, current_hand_transform, 10)
  File "/home/lakshmi/cat_OR_ws/src/raveutils/src/raveutils/planning.py", line 37, in plan_cartesian_twist
    delta_q = np.dot(Jpinv, delta)
ValueError: shapes (6,6) and (4,4) not aligned: 6 (dim 1) != 4 (dim 0)

````

And I see a function "plan_constant_velocity_twist" in planning.py , can I use this function for motion planning a robot to move in a straight line with a constant velocity?

**Comment by fsuarez6** [comment]
> `ValueError: shapes (6,6) and (4,4) not aligned: 6 (dim 1) != 4 (dim 0)`

This seems to be an issue with the number of DoFs. How many DoFs do you have?

Regarding straight line motion with constant velocity, `raveutils.planning.plan_constant_velocity_twist` might be useful for you. 

Refer to the tests for usage examples, e.g: https://github.com/crigroup/raveutils/blob/master/tests/test_planning.py#L45

**Comment by lakshmip001** [comment]
> > `ValueError: shapes (6,6) and (4,4) not aligned: 6 (dim 1) != 4 (dim 0)`
> 
> This seems to be an issue with the number of DoFs. How many DoFs do you have?
> I am using 6DOF UR5 arm.
> Regarding straight line motion with constant velocity, `raveutils.planning.plan_constant_velocity_twist` might be useful for you.
> I just have a doubt what does twist represent? and Is it something similar to descerates?
> Refer to the tests for usage examples, e.g: https://github.com/crigroup/raveutils/blob/master/tests/test_planning.py#L45

I refered to it .
 There are some distances taken .
Later obtains twist.

Can you help me understand what does distance respresent and what is twist 
```
np.random.seed(123)
    env = self.env
    robot = self.robot
    velocity = 0.002
    distances = [0.01, 0.02, 0.1, 0.5, 1.]
    for dist in distances:
      while True:
        q = ru.kinematics.random_joint_values(robot)
        with env:
          robot.SetActiveDOFValues(q)
        if not env.CheckCollision(robot):
          break
      twist = np.random.rand(6)*dist
      traj = ru.planning.plan_constant_velocity_twist(robot, twist, velocity)
    # Superpass velocity limits
    np.random.seed(123)
    velocity = 0.02
    twist = np.random.rand(6)*0.02
traj = ru.planning.plan_constant_velocity_twist(robot, twist, velocity)

'''

**Comment by fsuarez6** [comment]
Moving this discussion to #11
